
version: '3.8'

services:
  # Consul Server
  consul:
    image: hashicorp/consul
    container_name: consul
    ports:
      - "8500:8500"  # Consul UI
    volumes:
      - consul_data:/consul/data
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0
    networks:
      - app-network

  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # MongoDB default port
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

# Volumes for persistent data
volumes:
  consul_data:
  mongodb_data:

# Network for communication between services
networks:
  app-network:
    driver: bridge
